<?php

declare(strict_types=1);

namespace Inurlbr\Report;

use Inurlbr\Contracts\ReportGeneratorInterface;
use InurlBr\Models\Vulnerability;

/**
 * Generador de reportes en formato Markdown.
 */
class MarkdownReportGenerator implements ReportGeneratorInterface
{
    public function generate(array $results, array $metadata = []): string
    {
        $output = [];
        
        // Header
        $output[] = '# INURLBR Security Scan Report';
        $output[] = '';
        $output[] = '## Scan Information';
        $output[] = '';
        $output[] = "| Property | Value |";
        $output[] = "|----------|-------|";
        $output[] = "| **Date** | " . ($metadata['date'] ?? date('Y-m-d H:i:s')) . " |";
        $output[] = "| **Dork** | " . ($metadata['dork'] ?? 'N/A') . " |";
        $output[] = "| **Engine(s)** | " . ($metadata['engines'] ?? 'N/A') . " |";
        $output[] = "| **Total URLs Scanned** | " . ($metadata['total_urls'] ?? count($results)) . " |";
        $output[] = "| **Vulnerabilities Found** | **" . count($results) . "** |";
        $output[] = '';
        
        // Summary by severity
        if (!empty($results)) {
            $output[] = '## Summary by Severity';
            $output[] = '';
            
            $severityCount = [
                'CRITICAL' => 0,
                'HIGH' => 0,
                'MEDIUM' => 0,
                'LOW' => 0,
                'INFO' => 0,
            ];
            
            foreach ($results as $vuln) {
                if ($vuln instanceof Vulnerability) {
                    $severityCount[$vuln->severity]++;
                }
            }
            
            $output[] = "| Severity | Count |";
            $output[] = "|----------|-------|";
            foreach ($severityCount as $severity => $count) {
                if ($count > 0) {
                    $output[] = "| {$severity} | {$count} |";
                }
            }
            $output[] = '';
        }
        
        // Vulnerabilities detail
        if (!empty($results)) {
            $output[] = '## Vulnerabilities Found';
            $output[] = '';
            
            $i = 1;
            foreach ($results as $vuln) {
                if ($vuln instanceof Vulnerability) {
                    $output[] = "### #{$i} - {$vuln->type}";
                    $output[] = '';
                    $output[] = "| Property | Value |";
                    $output[] = "|----------|-------|";
                    $output[] = "| **URL** | `{$vuln->url}` |";
                    $output[] = "| **Severity** | **{$vuln->severity}** |";
                    $output[] = "| **Confidence** | {$vuln->confidence}% |";
                    $output[] = "| **Payload** | `{$vuln->payload}` |";
                    $output[] = '';
                    $output[] = '**Evidence:**';
                    $output[] = '';
                    $output[] = '```';
                    $output[] = $vuln->evidence;
                    $output[] = '```';
                    $output[] = '';
                    $output[] = '---';
                    $output[] = '';
                    
                    $i++;
                }
            }
        } else {
            $output[] = '## Results';
            $output[] = '';
            $output[] = '✅ No vulnerabilities were detected during this scan.';
            $output[] = '';
        }
        
        // Footer
        $output[] = '---';
        $output[] = '';
        $output[] = '*Generated by INURLBR v3.0 - Modern Security Scanner*';
        $output[] = '';
        $output[] = '> ⚠️ **Disclaimer**: This tool is for educational and authorized security testing only. Always obtain proper authorization before scanning any system.';
        
        return implode("\n", $output);
    }

    public function save(string $content, string $filename, ?string $directory = null): string
    {
        $directory = $directory ?? __DIR__ . '/../../output';
        
        // Crear directorio si no existe
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }
        
        $filepath = rtrim($directory, '/') . '/' . $filename . '.' . $this->getExtension();
        
        if (file_put_contents($filepath, $content) === false) {
            throw new \RuntimeException("Failed to save report to: {$filepath}");
        }
        
        return $filepath;
    }

    public function getExtension(): string
    {
        return 'md';
    }
}
